### ISSUE TITLE
[suggestion] Config options?

### ISSUE THREAD

**Issue by Mofo50C** [Azmalent/backported-flora#3]
Would it be possible if you could add a biome and dimension whitelist/blacklist to the configs, as well as a filter for which blocks the seagrass and kelp are generated on. Ive been trying to simulate the new 1.13 water biomes and what not with you're mod and i would greatly appreciate if these configs existed. other than that its a great mod.

**Comment by Azmalent** [comment]
Not sure about the filter, as I check the materials and not block IDs. In vanilla, kelp and seagrass can be planted on any non-transparent block.

Biome and dimension blacklists could be added though.

**Comment by Mofo50C** [comment]
> Not sure about the filter, as I check the materials and not block IDs. In vanilla, kelp and seagrass can be planted on any non-transparent block.
> 
> Biome and dimension blacklists could be added though.

Oh ok nah its because they were spawning in underwater caves so maybe allow a height limit as well that would be  nice in addition to biome and dimension.

Also im sure they're possible ive only made a couple simple mods but i looked at code of similar mods and it didnt look too difficult to add a check for dimension and biome to the world gen class of your own

**Comment by Mofo50C** [comment]
> Not sure about the filter, as I check the materials and not block IDs. In vanilla, kelp and seagrass can be planted on any non-transparent block.
> 
> Biome and dimension blacklists could be added though.

Oh ok nah its because they were spawning in underwater caves so maybe allow a height limit as well that would be  nice in addition to biome and dimension. Also im sure they're possible i don't know modding that much but i looked at code of similar mods and its probably not that difficult to add it to the world gen class of your own

**Comment by Mofo50C** [comment]
mb i accidentally closed it 😂

**Comment by Azmalent** [comment]
IMO checking if the block can see the sky is a better way to go about it.

**Comment by Mofo50C** [comment]
> IMO checking if the block can see the sky is a better way to go about it.

Oh ye youre right

**Comment by Azmalent** [comment]
Dimension and biome black/whitelists and underground seaweed configs have been added in 1.7.
